### ISSUE TITLE
水平效果文字重叠，希望图片改成自定义view

### ISSUE THREAD

**Issue by zhzhh7378** [baoyachi/StepView#13]
水平效果文字比较多怎么弄，直接用下面的字体会重叠
![image](https://cloud.githubusercontent.com/assets/14539415/16754048/7e7d2efc-4821-11e6-8218-5900ef72e9ac.png)

**Comment by baoyachi** [comment]
好的，已知晓。
前提：
  因为水平的StepView不易有好多步骤，若是步骤多，反而影响了用户体验，这是从用户体验角度来思考。考虑到有很多“变态的需求”，步骤就是有TM的七八步骤，产品提出的，程序员也没法反驳，只好硬着头皮做。所以，当真有这种需求的时候，我的思考方式是，判断两个圆之间一半的距离和当前对应文字的大小比，若是当前文字大于线的左边一半+圆直径+右圆一半，就换行，小于的话，文字就居中显示。当前【stepview】1.5的做法比较屎，稍后会做修改。谢谢。Have a nice day!Good luck.
🔢

**Comment by zhzhh7378** [comment]
我刚尝试自定义TabLayout来实现stepview的功能，失败了子view不显示。我觉得你可以试一下这样每一步就可以选择是固定宽度还是自适应宽度太多的话就可以滑动。

**Comment by baoyachi** [comment]
没明白什么意思啊？

**Comment by zhzhh7378** [comment]
![image](https://cloud.githubusercontent.com/assets/14539415/16762215/2b0dff6e-4856-11e6-9edb-5d31c32807db.png)
继承android.support.design.widget.TabLayout   `
`**
 * Created by Administrator on 2016/7/12.
 */
public class MyStepView extends TabLayout {
    List<String> lables;
    int cstep=0;
    public MyStepView(Context context) {
        super(context);
    }

    public MyStepView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyStepView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

    }

    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        if (changed) {
            int childLeft = 0;
            final int childCount = getChildCount();
            for (int i = 0; i < childCount; i++) {
                final View childView = getChildAt(i);
                if (childView.getVisibility() != View.GONE) {
                    final int childWidth = childView.getMeasuredWidth();
                    childView.layout(childLeft, 0, childLeft + childWidth,
                            childView.getMeasuredHeight());
                    childLeft += childWidth;
                }
            }
        }
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        final int count = getChildCount();
        for (int i = 0; i < count; i++) {
            getChildAt(i).measure(widthMeasureSpec, heightMeasureSpec);
        }
    }

    public MyStepView setLables(List<String> lables){
        this.lables=lables;
        return this;
    }
    public MyStepView setCurrStep(int curr){
        cstep=curr;
        return this;
    }
    public void init(){
        if(lables!=null){
            int i=1;
            for(String l:lables){
                StepItemView s=  new StepItemView(getContext());
                s.setIndex(i+"");
                s.setitemLable(l);
                if(i==0){
                    s.isStart(true);
                }
                if(i==lables.size()){
                    s.isEnd(true);
                }
                if(i<=cstep){
                    s.isOver(true);
                }else {
                    s.isOver(false);
                }
                View v=LayoutInflater.from(getContext()).inflate(R.layout.my_step_item_layout,this,false);
                addTab(newTab().setCustomView(v));
                i++;
            }
        }
    }



    public static class StepItemView extends ViewGroup{
        View lv,rv;
        TextView index,lable;


        public StepItemView(Context context) {
            super(context);
            initItem();
        }

        public StepItemView(Context context, AttributeSet attrs) {
            super(context, attrs);
            initItem();
        }

        public StepItemView(Context context, AttributeSet attrs, int defStyleAttr) {
            super(context, attrs, defStyleAttr);
            initItem();
        }

        @Override
        protected void onLayout(boolean changed, int l, int t, int r, int b) {
            if (changed) {
                int childLeft = 0;
                final int childCount = getChildCount();
                for (int i = 0; i < childCount; i++) {
                    final View childView = getChildAt(i);
                    if (childView.getVisibility() != View.GONE) {
                        final int childWidth = childView.getMeasuredWidth();
                        childView.layout(childLeft, 0, childLeft + childWidth,
                                childView.getMeasuredHeight());
                        childLeft += childWidth;
                    }
                }
            }
        }

        @Override
        protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
            final int count = getChildCount();
            for (int i = 0; i < count; i++) {
                getChildAt(i).measure(widthMeasureSpec, heightMeasureSpec);
            }
        }

        private void initItem() {
            View v=LayoutInflater.from(getContext()).inflate(R.layout.my_step_item_layout,this,false);
            lv=v.findViewById(R.id.left);
            rv=v.findViewById(R.id.right);
            index= (TextView) v.findViewById(R.id.index_text);
            lable= (TextView) v.findViewById(R.id.lable);
           addView(v);
        }
        public StepItemView setitemLable(String lb){
            lable.setText(lb);
            return this;
        }
        public StepItemView setIndex(String lb){
            index.setText(lb);
            return this;
        }
        public StepItemView isStart(boolean isStart){
            if(isStart)
            lv.setVisibility(INVISIBLE);
            return this;
        }
        public StepItemView isEnd(boolean isEnd){
            if(isEnd)
            rv.setVisibility(INVISIBLE);
            return this;
        }
        public StepItemView isOver(boolean isover){
            index.setEnabled(!isover);
            if(isover){
                rv.setBackgroundColor(getResources().getColor(R.color.green));
                lv.setBackgroundColor(getResources().getColor(R.color.green));
                lable.setTextColor(getResources().getColor(R.color.green));
            }else {
                rv.setBackgroundColor(getResources().getColor(R.color.gray));
                lv.setBackgroundColor(getResources().getColor(R.color.gray));
                lable.setTextColor(getResources().getColor(R.color.gray));
            }

            return this;
        }


    }




}`

这是我的思路，可是没弄好。t
