### ISSUE TITLE
minSdkVersion 16

### ISSUE THREAD

**Issue by andansky** [baoyachi/StepView#16]
minSdkVersion 16
这个最小一定要是16的吗，我的项目是15然后gradle导入你这个包冲突了。。。。。

**Comment by baoyachi** [comment]
@andansky 已经兼容14了，因为当初创建时选的是16，兼容到14，应该没什么问题

**Comment by andansky** [comment]
那现在我的冲突了怎么解决啊？只能下载你的代码通过修改源码的方式来解决吗？我是用gradle 直接compile你的项目来用的呢。

**Comment by baoyachi** [comment]
@andansky 我已经更新gradle版本了

```java
compile 'com.github.baoyachi:StepView:1.7.1'
```

**Comment by andansky** [comment]
好了。非常感谢
