### ISSUE TITLE
为什么会显示成这样？

### ISSUE THREAD

**Issue by LiHeng** [baoyachi/StepView#18]
![screenshot_2016-07-26-17-07-16](https://cloud.githubusercontent.com/assets/17843524/17132623/242206d2-5355-11e6-977a-527de28957bb.png)

**Comment by baoyachi** [comment]
@LiHeng Hi,it's been updated。
Now,you can update you gradle  version 
```java
compile 'com.github.baoyachi:StepView:1.8'
```
Have a nice day! 🔢
