### ISSUE TITLE
how to update stepsViewIndicatorComplectingPosition

### ISSUE THREAD

**Issue by GauravP123** [baoyachi/StepView#19]
`setpview0.setStepsViewIndicatorComplectingPosition(1)//设置完成的步数
                .setStepViewTexts(list0)//总步骤
                .setTextSize(16)//set textSize
                .setStepsViewIndicatorCompletedLineColor(ContextCompat.getColor(getActivity(), android.R.color.white))//设置StepsViewIndicator完成线的颜色
                .setStepsViewIndicatorUnCompletedLineColor(ContextCompat.getColor(getActivity(), R.color.uncompleted_text_color))//设置StepsViewIndicator未完成线的颜色
                .setStepViewComplectedTextColor(ContextCompat.getColor(getActivity(), android.R.color.white))//设置StepsView text完成线的颜色
        ;`
i am making one global variable of HorizontalStepView and setting up. 

 then when user click on button i am calling 
`mView.findViewById(R.id.an).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                 setpview0.setStepsViewIndicatorComplectingPosition(3);
               
            }
        });` 

but it is not updating

**Comment by baoyachi** [comment]
are you using new version in you gardle？

**Comment by GauravP123** [comment]
I am using Gradle version -2.10
Andorid plugin version - 2.1.0
 MinSdkVersion -14

**Comment by GauravP123** [comment]
So for now to get work i have to create horizontalview public variable and then call invalidate but this patch work I think so

**Comment by baoyachi** [comment]
@GauravP123 Let me try！

**Comment by GauravP123** [comment]
any update?

**Comment by GauravP123** [comment]
hi have u fine ant thing ?

**Comment by baoyachi** [comment]
@GauravP123 
I‘m so sorry about you,Recently because I’m so busy in work!Just I find this pass parme have a little problem？

**Comment by baoyachi** [comment]
@GauravP123 
hi ,I’m so sorry about you !
<img width="675" alt="5aea6b32-2946-46ae-9149-cf2410c8c1e6" src="https://cloud.githubusercontent.com/assets/10433001/17728426/c017216a-6491-11e6-9885-8b8ef0249fe8.png">

**Comment by GauravP123** [comment]
but when i want to update on button click  and i add setviewindicatorecomplectingpo(3) then its not moving from 1-3

**Comment by baoyachi** [comment]
Hi,@GauravP123  you can see this[【issues23】](https://github.com/baoyachi/StepView/issues/23)
