### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by action-hong** [baoyachi/StepView#6]
为什么不搞一个取出当前到第几步的方法?
这样不就可以动态实现跑到下一步还是回到上一步

`
public void click(View v){
        int currentPosition = stepViewSelf.getStepsViewIndicatorComplectingPosition();
        switch (v.getId()){
            case R.id.plus:
                if(currentPosition == list0.size()-1) return;
                stepViewSelf.setStepsViewIndicatorComplectingPosition(++currentPosition);
                break;
            case R.id.dec:
                if(currentPosition == 0) return;
                stepViewSelf.setStepsViewIndicatorComplectingPosition(--currentPosition);
                break;
        }
    }

public void setmComplectingPosition(int mComplectingPosition) {
        this.mComplectingPosition = mComplectingPosition;
        invalidate();
    }
`

**Comment by baoyachi** [comment]
Yeah,it's good idea,but this is example for display,so ,just simple so.Thank you suggest! Thank you.
