### ISSUE TITLE
VerticalStepViewIndicator.OnDrawIndicatorListener

### ISSUE THREAD

**Issue by Uphie** [baoyachi/StepView#8]
一个小问题，虽然在这个控件库中没有问题，但我觉得编程中应该是要注意的。
VerticalStepViewIndicator的onDraw()方法的第二句，mOnDrawListener是由外面设置的，此处使用时需要判断是否为null，在预览widget_vertical_stepsview.xml时可以看到的。
```
 if (mOnDrawListener!=null){
            mOnDrawListener.onDrawIndicator();
   }
```
相同的问题有4个。

**Comment by baoyachi** [comment]
Thank you very much！It's been fixed
